# Generated by Django 2.0.9 on 2026-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregister',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
