# Generated by Django 2.0.9 on 2026-06-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sellerregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregister',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
