# Generated by Django 2.0.9 on 2026-06-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_catagories_product_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagories',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Product_details',
            new_name='Productdetails',
        ),
    ]
